name: Build on Windows

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**.yml'
      - '{external,src}/**.{c,cpp,h,hpp}'
      - 'trigger-build.txt'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/workflows/**.yml'
      - '{external,src}/**.{c,cpp,h,hpp}'
      - 'trigger-build.txt'

env:
  CMAKE_RELEASE_PRESET_NAME: Release
  CMAKE_RELEASE_CONFIG_NAME: Release
  CMAKE_RELEASE_OUTPUT_PATTERN: build/Windows/Release/Release/*
  CL_CC: cl
  CL_CXX: cl
  HL2SDK_BRANCH: cs2
  HL2SDK_ROOT: external\hl2sdk-cs2
  MMSOURCE_ROOT: external\metamod-source

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Get absolute path
      id: get_path-windows
      if: runner.os == 'Windows'
      run: |
        $path = (Get-Location).Path
        echo "ABSOLUTE_PATH=$path" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Checkout HL2SDK
      uses: actions/checkout@v4
      with:
        repository: Wend4r/hl2sdk
        ref: ${{ env.HL2SDK_BRANCH }}
        path: ${{ env.HL2SDK_ROOT }}

    - name: Checkout MetaMod:Source
      uses: actions/checkout@v4
      with:
        repository: alliedmodders/metamod-source
        path: ${{ env.MMSOURCE_ROOT }}

    - name: Release - Configure CMake
      run: >
        cmake --preset ${{ env.CMAKE_RELEASE_PRESET_NAME }}
        -DCMAKE_C_COMPILER=${{ env.CL_CC }}
        -DCMAKE_CXX_COMPILER=${{ env.CL_CXX }}
        -DSOURCESDK_DIR=${{ env.ABSOLUTE_PATH }}\${{ env.HL2SDK_ROOT }}
        -DMETAMOD_DIR=${{ env.ABSOLUTE_PATH }}\${{ env.MMSOURCE_ROOT }}

    - name: Release - Build
      run: cmake --build --preset ${{ env.CMAKE_RELEASE_PRESET_NAME }} --parallel --config ${{ env.CMAKE_RELEASE_CONFIG_NAME }}

    - name: Release - Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ env.CMAKE_RELEASE_PRESET_NAME }}
        path: ${{ env.CMAKE_RELEASE_OUTPUT_PATTERN }}
