name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  HL2SDK_BRANCH: cs2
  HL2SDK_ROOT: ${{ github.workspace }}/hl2sdk-cs2
  MMSOURCE_ROOT: ${{ github.workspace }}/metamod-source

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            preset: Windows/Release
            artifact_pattern: build/Release/Release/*
            build_type: Release
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            preset: Release
            artifact_pattern: build/Release/*.so
            build_type: Release
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            preset: Release
            artifact_pattern: build/Release/*.so
            build_type: Release
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build

    - name: Checkout HL2SDK
      uses: actions/checkout@v4
      with:
        repository: Wend4r/hl2sdk
        ref: ${{ env.HL2SDK_BRANCH }}
        path: ${{ env.HL2SDK_ROOT }}

    - name: Checkout MetaMod:Source
      uses: actions/checkout@v4
      with:
        repository: alliedmodders/metamod-source
        path: ${{ env.MMSOURCE_ROOT }}

    - name: Configure CMake
      run: >
        cmake --preset ${{ matrix.preset }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DSOURCESDK_DIR=${{ env.HL2SDK_ROOT }}
        -DMETAMOD_DIR=${{ env.MMSOURCE_ROOT }}
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build --config ${{ matrix.build_type }} ---parallel --preset ${{ matrix.preset }}

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ runner.os }}-${{ matrix.c_compiler }}
        path: ${{ matrix.artifact_pattern }}
